WebApplication1/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication2.Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "User")]
    public class BookingsController : Controller
    {
        private readonly MyDbContext _context;

        public BookingsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
              return _context.Booking != null ? 
                          View(await _context.Booking.ToListAsync()) :
                          Problem("Entity set 'MyDbContext.Booking'  is null.");
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,PhoneNumber,SelectEventDate,SelectEventStartingTime,SelectHotel,SelectEvent,SelectEventTiming,TotalNumberOfGuests")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Email,PhoneNumber,SelectEventDate,SelectEventStartingTime,SelectHotel,SelectEvent,SelectEventTiming,TotalNumberOfGuests")] Booking booking)
        {
            if (id != booking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Booking == null)
            {
                return Problem("Entity set 'MyDbContext.Booking'  is null.");
            }
            var booking = await _context.Booking.FindAsync(id);
            if (booking != null)
            {
                _context.Booking.Remove(booking);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
          return (_context.Booking?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication1/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ContactsController : Controller
    {
        private readonly MyDbContext _context;

        public ContactsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
              return _context.Contact != null ? 
                          View(await _context.Contact.ToListAsync()) :
                          Problem("Entity set 'MyDbContext.Contact'  is null.");
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contact == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,Message")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Contact == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.FindAsync(id);
            if (contact == null)
            {
                return NotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,Message")] Contact contact)
        {
            if (id != contact.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactExists(contact.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Contact == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Contact == null)
            {
                return Problem("Entity set 'MyDbContext.Contact'  is null.");
            }
            var contact = await _context.Contact.FindAsync(id);
            if (contact != null)
            {
                _context.Contact.Remove(contact);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
          return (_context.Contact?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication1/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;


    using global::WebApplication1.Data;
    using global::WebApplication1.Models;
    using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;


namespace WebApplication1.Controllers

{
    // [Authorize(Roles = "User")]
    public class UserController : Controller
    {
        private MyDbContext _db;
        private IWebHostEnvironment _webHostEnvironment;

        private readonly UserManager<ApplicationUser> _userManager;
        public UserController(MyDbContext db, UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Home()
        {
            return View();
        }


        public async Task<IActionResult> IndexUserAsync()
        {
            var booking = _db.Booking;
            return View(booking);
        }

        public IActionResult Bookings()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            Booking booking = _db.Booking.Find(id);
            return View(booking);
        }

    }
}

WebApplication1/Views/Shared/_AdminLayout .cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventHUB</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/mycsstheme.css" />
    <link rel="stylesheet" href="~/css/google_btn.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

    <style>
        .Footer {
            background-color: #222222;
            color: #fff;
            padding: 2rem 0;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        #raw {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }

        .ft-1 #eve {
            color: #dfd4d4;
            font-weight: 700;
            letter-spacing: 2px;
            padding: 0.5rem 0;
        }



        .ft-1 #para {
            padding: 0.5rem 2rem 1rem 0;
        }

        .footer-icons i {
            margin-top: 20px;
            margin-right: 10px;
            padding: 0.5rem;
            background: #fff;
            color: #888888;
            border-radius: 50px;
            margin-bottom: 30px;
        }

            .footer-icons i:hover {
                background: #888888;
                color: #fff;
                transition: 0.6s;
                cursor: pointer;
            }

        .ft-3 {
            color: #dfd4d4;
        }

        .ft-2 h5 {
            color: #dfd4d4;
        }

        .ft-2 ul {
            margin-top: 30px;
        }

        .ft-2 a {
            color: #fff;
        }

        .ft-4 .contact {
            margin-top: 30px;
        }

        .ft-4 h5 {
            color: #dfd4d4;
        }

        .ft-4 i {
            margin-right: 10px;
        }

        .footer-wrap {
            text-align: center;
            background: #888888;
            padding-top: 10px;
            padding-bottom: 10px;
        }

            .footer-wrap p {
                color: #fff;
                font-size: medium;
                font-weight: 700;
                margin-bottom: 0;
            }
    </style>
</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventHUB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Create">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="GetUsers">User Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="IndexUser">Booking Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="">Queries</a>
                        </li>
                        
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container pt-3">
        <main role="main" class="pb-3 pt-5">
            @RenderBody()
        </main>
    </div>

    <div class='Footer'>
        <div class='container'>
            <div class='row' id="raw">
                <div class='col-md-6 col-lg-3  col-12 ft-1'>
                    <h4 id="eve">EventHUB</h4>
                    <p id="para">
                        EventHub is a cutting-edge event management system designed to streamline and enhance your event planning experience.
                        Whether you're organizing corporate conferences, weddings, birthday parties, or any other special occasions,
                        EventHub provides a comprehensive suite of tools to make your events a resounding success.
                    </p>
                </div>
                <div class='col-md-6 col-lg-2  col-12 ft-2'>
                    <h5>Quick Links</h5>
                    <ul>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contacts" asp-action="Create">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Services">Services</a>
                        </li>
                    </ul>
                </div>
                <div class='col-md-6 col-lg-3  col-12 ft-3'>
                    <h5>Follow EventHUB</h5>
                    <div class='footer-icons'>
                        <i class="fab fa-facebook"></i>
                        <i class="fa-brands fa-x-twitter"></i>
                        <i class="fab fa-instagram"></i>
                        <i class="fab fa-youtube"></i>
                    </div>
                </div>
                <div class='col-md-6 col-lg-3  col-12 ft-4'>
                    <h5>Contact Info</h5>
                    <div class='contact'>
                        <p><i class="fas fa-phone-volume"></i>+91 9867253789</p>
                        <p><i class="fas fa-envelope"></i>test@gmail.com</p>
                        <p><i class="fas fa-map-marker"></i>Mumbai, Maharashtra, India.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='footer-wrap'>
        <p>
            Copyright. EventHUB, All rights reserved.
        </p>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventHUB</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/mycsstheme.css" />
    <link rel="stylesheet" href="~/css/google_btn.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

    <style>
        .Footer {
            background-color: #222222;
            color: #fff;
            padding: 2rem 0;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        #raw {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }

        .ft-1 #eve {
            color: #dfd4d4;
            font-weight: 700;
            letter-spacing: 2px;
            padding: 0.5rem 0;
        }



        .ft-1 #para {
            padding: 0.5rem 2rem 1rem 0;
        }

        .footer-icons i {
            margin-top: 20px;
            margin-right: 10px;
            padding: 0.5rem;
            background: #fff;
            color: #888888;
            border-radius: 50px;
            margin-bottom: 30px;
        }

            .footer-icons i:hover {
                background: #888888;
                color: #fff;
                transition: 0.6s;
                cursor: pointer;
            }

        .ft-3 {
            color: #dfd4d4;
        }

        .ft-2 h5 {
            color: #dfd4d4;
        }

        .ft-2 ul {
            margin-top: 30px;
        }

        .ft-2 a {
            color: #fff;
        }

        .ft-4 .contact {
            margin-top: 30px;
        }

        .ft-4 h5 {
            color: #dfd4d4;
        }

        .ft-4 i {
            margin-right: 10px;
        }

        .footer-wrap {
            text-align: center;
            background: #888888;
            padding-top: 10px;
            padding-bottom: 10px;
        }

            .footer-wrap p {
                color: #fff;
                font-size: medium;
                font-weight: 700;
                margin-bottom: 0;
            }
    </style>
</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventHUB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Services">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Create">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Create">New Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Stories">Customer Stories</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container pt-3">
        <main role="main" class="pb-3 pt-5">
            @RenderBody()
        </main>
    </div>

    <div class='Footer'>
        <div class='container'>
            <div class='row' id="raw">
                <div class='col-md-6 col-lg-3  col-12 ft-1'>
                    <h4 id="eve">EventHUB</h4>
                    <p id="para">
                        EventHub is a cutting-edge event management system designed to streamline and enhance your event planning experience.
                        Whether you're organizing corporate conferences, weddings, birthday parties, or any other special occasions,
                        EventHub provides a comprehensive suite of tools to make your events a resounding success.
                    </p>
                </div>
                <div class='col-md-6 col-lg-2  col-12 ft-2'>
                    <h5>Quick Links</h5>
                    <ul>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contacts" asp-action="Create">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Services">Services</a>
                        </li>
                    </ul>
                </div>
                <div class='col-md-6 col-lg-3  col-12 ft-3'>
                    <h5>Follow EventHUB</h5>
                    <div class='footer-icons'>
                        <i class="fab fa-facebook"></i>
                        <i class="fa-brands fa-x-twitter"></i>
                        <i class="fab fa-instagram"></i>
                        <i class="fab fa-youtube"></i>
                    </div>
                </div>
                <div class='col-md-6 col-lg-3  col-12 ft-4'>
                    <h5>Contact Info</h5>
                    <div class='contact'>
                        <p><i class="fas fa-phone-volume"></i>+91 9867253789</p>
                        <p><i class="fas fa-envelope"></i>test@gmail.com</p>
                        <p><i class="fas fa-map-marker"></i>Mumbai, Maharashtra, India.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='footer-wrap'>
        <p>
            Copyright. EventHUB, All rights reserved.
        </p>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>